# Generated by Django 4.1.5 on 2023-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='long_url',
            field=models.URLField(unique=True),
        ),
    ]
