# Generated by Django 4.1.5 on 2023-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_shortenedurl_long_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='long_url',
            field=models.URLField(),
        ),
    ]
